# docker-compose up --build
version: "3"
services:
  backend-node-js:
    container_name: node-js-ts
    networks:
      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: production
    ports:
      - 8080:8080
networks:
  api_server_default:
    external: true